microsoft/MSCloudLoginAssistant

MSCloudLoginAssistant.psm1
Pnp needs to connect to the ConnectionUrl passed, or to central admin by default
=> Fixes Regression bug on PnP connection

MSCloudLoginAssistant.psm1
Pnp throws a generic error message when an MFA account is used to call connect-pnponline without the -UseWebLogin parameter. I've added a check to see if the platform is PnP, and check for the generic error pattern in order to "Assume" MFA is required.
=> Fix for PnP MFA Auth flow

Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
Added up to 10 retries (60 seconds wait) for Security and Compliance when all sessions are already in use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/15)
=> Error handling for Security and Compliance

Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
As weird as it sounds, this is not related to the previous Skype for Business PR, but to the upgrade to MicrosoftTeams 1.0.3 which now complains about a missing Connect-MicrosoftTeams cmdlet. The fix is to implicitly load the module within the switch case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/28)
=> Fix error with 1.0.3 with Connect-MicrosoftTeams

Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
Fixes an issue where if you tried connecting to PnP right after connecting to Security and Compliance, then PnP tries to call Connect-PnPService with an empty URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/42)
=> Fix for PnP connection

Modules/MSCloudLoginAssistant/Workloads/Teams.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/43)
=> Remove mandatory Environment name for Teams with MFA

Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1, Modules/MSCloudLoginAssistant/Workloads/Azure.psm1
Set-AzContext now also uses sub name as sometimes wrong one being set
Increment version for gallery to 1.0.11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/60)
=> Quick update to Azure.psm1

Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1, Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
PNP now throws a different error message if you don't specify -useweblogin and use a MFA enabled account
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/92)
=> Fixed issue with MFA enabled accounts and PNP

Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1, Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
Export of SCSensitivityLabels was failing because runspaces were closed. Added a check for SkipModuleReload and it resolved issue can export resources as well as run apply config with multiple resources within SCC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/104)
=> Fix for extract of SCC resources

Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
The `ActiveSessions[0]` might have been closed by the loop after.
This caused an error while trying to use `Import-PSSession` on an already closed and disposed session.
To fix this, just check for active sessions after closing the already open connections
=> Fixed check for active sessions in Security & Compliance

Modules/MSCloudLoginAssistant/Workloads/SkypeForBusiness.psm1
The connection would always fail on the first connection since it throws the error caused by connection needing MFA.
=> Fixes MFA login in SkypeForBusiness

Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
This cause a lot of unwanted noise when verbose output is not wanted.
By removing it, the user can decide if they want verbose output or not with `-Verbose` parameter
=> SecurityCompliance: Removed verbose being  set to continue

Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1, Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1, Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
This PR adds better detection and logging for Device Code authentication requests. In non-interactive sessions, requesting a Device Code logon doesn't make sense and just adds additional waiting time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/118)
=> Added more detection and proper logging for DeviceCode errors

Modules/MSCloudLoginAssistant/ConnectionProfile.psm1, Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1, Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
Add support for VM MSI using Login-AzAccount -Identity and Get-AzAccessToken -ResourceTypeName MSGraph.  This could be extended to AzureAD and Azure using same pattern
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/123)
=> Add MSI support for MSGraph

Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
To support CredentialsWithApplicationId, adds missing TenantId and ClientId parameters to Connect-MgGraph connection command.
Changes requested Scopes to generic .default
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/135)
=> Fixes #134 - Connect-MSCloudLoginMSGraphWithUser missing profile parameters

Modules/MSCloudLoginAssistant/ConnectionProfile.psm1, Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1, Modules/MSCloudLoginAssistant/Workloads/PnP.psm1, Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
EXO V3 supports now the certificate-based authentication to Security & Compliance PowerShell, both with thumbprint and certificate path: https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#connection-examples
I have added both authentication types to the workload.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/133)
=> Add Service Principal with Certrificate Authentication methods for Security and Compliance Center

Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
Three changes to the code for connecting using service principal and thumbprint:
1. $Global:MSCloudLoginConnectionProfile.OrganizationName was null and needs to have a value in order to connect
2. Connection parameters should be pulling from $Global:MSCloudLoginConnectionProfile.SecurityComplianceCenter, not $Global:MSCloudLoginConnectionProfile.ExchangeOnline
3. ShowProgress is not a valid parameter for Connect-IPPSSession
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/178)
=> Fix security compliance

Modules/MSCloudLoginAssistant/ConnectionProfile.psm1, Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1, Modules/MSCloudLoginAssistant/Workloads/ExchangeOnline.psm1
@NikCharlebois
This PR is an attempt at making the EXO command import smarter so that a user of the module can specify, which cmdlets of the EXO module to import. This results in a massively reduced memory consumption if only specific cmdlets are loaded. 
The suggestion of this PR comes from https://github.com/microsoft/Microsoft365DSC/issues/3956. 
Three new values are added to the `ExchangeOnline` workload: 
* `CmdletsToLoad` - The cmdlets of the EXO module to load
* `LoadedCmdlets` - An internal variable that holds the currently loaded cmdlets
* `LoadedAllCmdlets` - An internal variable that tells if all cmdlets of the EXO module were loaded
The approach is designed to increasingly load the new cmdlets (if specified), and if none are specified (by either omitting the new parameter …
=> Add EXO command import handling

Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1, Modules/MSCloudLoginAssistant/Workloads/Teams.psm1
Error:
```
The process cannot access the file 'Microsoft.Exchange.TransportMailflow-Help.xml' because it is being used by another process.
+ CategoryInfo          : WriteError: (Microsoft.Excha...ilflow-Help.xml:) [], CimException
+ FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
+ PSComputerName        : localhost
The directory is not empty.
+ CategoryInfo          : WriteError: (en-us:) [], CimException
+ FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
+ PSComputerName        : localhost
The directory is not empty.
+ CategoryInfo          : WriteError: (C:\Windows\Syst...XO_jcuznfih.par:) [], CimException
+ FullyQualifiedErrorId : …
```
=> Fixing issue in SC where an exception was thrown during reloading of module because of files that were still in use

Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This PR fixes an issue introduced in version 1.1.16 https://github.com/microsoft/MSCloudLoginAssistant/commit/1e29cf214a471c2c61dd67a146cc3fed24bf2b99. The comparison between `referenceObj`, which is in fact a `ValueCollection`, and an array of values does not use the same comparison technique. 
While `Compare-Object` successfully compares two arrays of values with each other, comparing a `ValueCollection` against an array will always lead to a difference, no matter the contents of the objects. This leads to an false positive of `Compare-InputParametersForChange`, which in terms means that those workloads without a dedicated check outside of `Connected` being true / false will always reconnect on every call to `Connect-M365Tenant`. Best example is the MicrosoftGraph workload: Without the …
=> Fix ValueCollection comparison against array

Modules/MSCloudLoginAssistant/ConnectionProfile.ps1, Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1, Modules/MSCloudLoginAssistant/Workloads/Azure.ps1, Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.ps1, Modules/MSCloudLoginAssistant/Workloads/PnP.ps1, Modules/MSCloudLoginAssistant/Workloads/Teams.ps1
This PR removes the unnecessary `Write-Verbose $PSScriptRoot -Verbose` statement from the top of the module and adds four more disconnect methods to the workloads: 
* Azure: Disconnect-MSCloudLoginAzure
* Microsoft Graph: Disconnect-MSCloudLoginMicrosoftGraph
* PnP: Disconnect-MSCloudLoginPnP
* Teams: Disconnect-MSCloudLoginTeams
The connection context is only reset if a disconnect for all workloads is done. Otherwise, an event will be logged and the connection will not be terminated for this workload.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/189)
=> Enable more workload disconnects

Modules/MSCloudLoginAssistant/Workloads/PnP.ps1
Fix authentication issues with Managed Identity and Azure Automation by appling the same fix from https://github.com/microsoft/MSCloudLoginAssistant/pull/175 that was applied to Microsoft Graph workload.
Since the 14th of October I started receiving some errors "An error has occurred Unable to connect to the remote server".
Adding some logs showed this additional error message:
>A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 169.254.169.254:80
This is the case where AzureAutomation is not recognized and $env:IDENTITY_ENDPOINT is not used.
These are the values of the environment variables in those cases:
IDENTITY_ENDPOINT: …
=> Fix authentication issues with Managed Identity and Azure Automation

Modules/MSCloudLoginAssistant/Workloads/ExchangeOnline.ps1
Follow up from https://github.com/microsoft/Microsoft365DSC/issues/5615.
This PR removes two calls to `Get-AcceptedDomain` to reduce the network load and improve overall speed.
The first call to `Get-AcceptedDomain` makes sure that the EXO module is loaded and has a connection. The availability of the module can also be checked if `Get-Command` returns an output and does not throw with the message that the command is not available. Connection issues in other workloads (e.g. an expired token) are normally not handled. 
The second call is just a duplicate in the first load that does not have any impact. As soon as `Connect-ExchangeOnline` is called, the session will be enabled and all connections alive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Reduce web calls to Exchange Online

Modules/MSCloudLoginAssistant/ConnectionProfile.ps1, Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1, Modules/MSCloudLoginAssistant/Workloads/PnP.ps1, Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.ps1
This PR contains the following two fixes: 
* Fixes an issue with the `Disconnect` method test where previously an error would be thrown if the method didn't exist
* Fixes an issue with resolving parameter sets in the PnP workload and credentials (and with application id) sign-in
* Fixes a typo in the SecurityCompliance workload where `AccessToken` was written without a trailing `s`
Fixes the following issue: 
- Fixes #191 
- Fixes #180
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/195)
=> Fix invalid parameter sets, disconnect test and typo

Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1, Modules/MSCloudLoginAssistant/Workloads/PnP.ps1
Add `CredentialsWithApplicationId` to supported authentication methods for the PnP workload. 
- Fixes https://github.com/microsoft/Microsoft365DSC/issues/4567
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/198)
=> Add CredentialsWithApplicationId to PnP workload

Modules/MSCloudLoginAssistant/CustomEnvironment.ps1
This PR fixes module import errors regarding non-existing properties in the `$Global:CustomTasks` and `$Global:CustomSharePointOnlineREST` variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/204)
=> Fix module import errors

Modules/MSCloudLoginAssistant/Workloads/Azure.ps1
Add existing connection check logic to start of Connect-MSCloudLoginAzure to allow connection re-use
Fixes [#210]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/214)
=> Add logic for Azure connection re-use on Connect-MSCloudLoginAzure

Modules/MSCloudLoginAssistant/Workloads/Azure.ps1
This PR fixes an issue with the login using access tokens in the Azure workload. `AccessTokens` is an array and only the first element contains the real access token, therefore we index into the first element. Additionally, using `-AccessToken` with `Connect-AzAccount` requires that the `-AccountId` parameter is specified as well. The description is the following: 
> Id for Account, associated with your access token. In User authentication flows, the AccountId is user name / user id; In AccessToken flow, it is the AccountId for the access token; In ManagedService flow, it is the associated client Id of UserAssigned identity. To use the SystemAssigned identity, leave this field blank.
After testing, it doesn't matter if the "correct" identity of the access token is used. Any value in the …
=> Fix Azure AccessToken login
