microsoft/MSCloudLoginAssistant

- .gitignore
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
Leveraging ADAL and Token Cache
> Improvement to reduce the number of MFA prompt

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Tests/TestHarness.psm1
- Tests/Unit/MSCloudLoginAssistant/MSCloudLoginAssistant.Tests.ps1
- Tests/Unit/Stubs/Stubs.psm1
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/9)
> Bogus PR to test Tests

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/11)
> Throws meaningful error and improve PnP flow

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
Minor formatting/syntax updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/10)
> Updated version number for Gallery

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/13)
> Update TenantInfo to use ConvertFrom-json

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
Clean up trailing white space etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/14)
> Don't prompt for windows-style creds for Azure

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/16)
> Added a catch for when PnP can't connect to site

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/17)
> Incremented version number to 0.7.1

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
Support for US, China and Germany + GCCH & DoD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/18)
> Azure clouds

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/23)
> Introducing Support for Germany Cloud

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/24)
> Incremented module version

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
S4B connection is required to interact with Teams Calling and meeting settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/26)
> Adds support for Skype For Business

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/27)
> Increment version number for gallery

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/29)
> Increment ModuleVersion for gallery

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Dynamically obtain TargetURI
- Dynamically obtain S4B Client ID
- Dynamically obtain AuthURI
- Handles the Access Token acquisition process on a separate thread using scheduler and change back to threading context to the main thread for the rest of the code to continue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/30)
> Major revamp for the S4B workload

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/31)
> Fixes MultiThreading around new context acquisition

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
Title says it all ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/33)
> Adds Support for PowerPlatforms

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/34)
> Support added for GCCH connection to Power Platform

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/35)
> Mostly spacing/style/spelling but also check for new AzureAD exception

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/36)
> Support for GCCH and Streamlined Logic for EXO and AzureAD

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/37)
> Increment version number to 0.8.4 for gallery.

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/PowerPlatform.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/39)
> Updates for Exchange MFA

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/41)
> Minor updates, ModuleVersion etc.

- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/52)
> Fix for PnP MFA

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/Azure.psm1
Re-enabled support for Verbose output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/51)
> Re-enabled "Test" functionality for Azure platform

- appveyor.yml
Added install-module AzureADPreview. It's required to be available for the module to load.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/55)
> Fix for Appveyor

- Modules/MSCloudLoginAssistant/Workloads/ExchangeOnline.psm1
- Modules/MSCloudLoginAssistant/Workloads/SkypeForBusiness.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/58)
> Fix regression bug introduced with Prefix

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/AzureAD.psm1
- Modules/MSCloudLoginAssistant/Workloads/ExchangeOnline.psm1
- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
- Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/61)
> Introduced support for MS Graph and Leverage new EXO v2 PowerShell

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/Workloads/ExchangeOnline.psm1
- Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/63)
> Fixed MFA Issue with Exchange and SC

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/Workloads/Azure.psm1
- Modules/MSCloudLoginAssistant/Workloads/AzureAD.psm1
- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
- Modules/MSCloudLoginAssistant/Workloads/SharePointOnline.psm1
- Modules/MSCloudLoginAssistant/Workloads/Teams.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/65)
> Explicitly import certain modules to avoid ambiguity with duplicate cmdlet names in different modules

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/69)
> Fixes for MSGraph

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
Added support to connect to SharePoint PNP with certificate path and certificate password
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/74)
> Add support for certpath and certpassword on PNP

- Modules/MSCloudLoginAssistant/Workloads/SkypeForBusiness.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/83)
> Fixes issue with Uppercase domain names in username

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/84)
> Release 1.0.34

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
- Modules/MSCloudLoginAssistant/Workloads/SkypeForBusiness.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/86)
> Release 1.0.36

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraphBeta.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/93)
> Added MSGraph Beta handler

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/95)
> Updated version to 1.0.44

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/96)
> Error handling

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/99)
> Changes to Runspace Management

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
This PR fixes two issues in the module:
- Fixes #102 
- Fixes #103
> Fixed issues #102 and #103

- Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
Issue: https://github.com/microsoft/MSCloudLoginAssistant/issues/100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/101)
> changed common endpoint to organizations

- Modules/MSCloudLoginAssistant/Workloads/ExchangeOnline.psm1
- Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
Changes required for EXO 2.0.4 PowerShell module for EXO and SCC workloads
> Changes for EXO 2.0.4 PowerShell 

- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
Code raised error if credentials where expired
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/113)
> Fixed bug when invalid creds entered

- Modules/MSCloudLoginAssistant/ConnectionProfile.psm1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/Intune.psm1
- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
- Modules/MSCloudLoginAssistant/Workloads/PowerPlatform.psm1
- Modules/MSCloudLoginAssistant/Workloads/Teams.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/117)
> Changes for DOD and GCCH connections

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
partial fix for #124 
This will update the description of Test-MSCloudLogin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/125)
> partial fix #124

- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/126)
Per conversation with @Nik, remove dependency on Az.Accounts and use REST call to managed identity endpoint.  Leverages specified Environment for correct Graph endpoint token request.
> Replace Login-AzAccount with REST call to MI endpoint

- Modules/MSCloudLoginAssistant/ConnectionProfile.psm1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/ExchangeOnline.psm1
- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
Add
> MI support for EXO authentication (requires EXO 3.0) (ExchangeOnline)
> Environment retrieval when using MI (ConnectionProfile)
> MI support for Get-MSCloudLoginOrganizationName/Get-TenantDomain (MSCloudLoginAssistant)
> Environment param when connecting with MI to MS Graph (MicrosoftGraph)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/129)
> Additional support for managed identity

- .vscode/ScriptAnalyzerSettings.psd1
- .vscode/settings.json
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/Azure.psm1
- Modules/MSCloudLoginAssistant/Workloads/ExchangeOnline.psm1
- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
Update to support managed identity for PnP workload.  Workaround for open bug #[2469](https://github.com/pnp/powershell/issues/2469)
Update vscode to match Microsoft365DSC
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/131)
> Update to support managed identity for PnP workload.

- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
connectionUrl was incorrectly set to $Url (repurposed bool for forcedRefresh) instead of PnP.ConnectionUrl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/132)
> Correct Url setting

- Modules/MSCloudLoginAssistant/ConnectionProfile.psm1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Fixes issue where DOD & GCCH failed to connect when running multiple workloads in same session. Cloud environment was 
reset was to AzureCloud when running multiple workloads in same session. 
- Fixed issue where detecting default domain in GCCH and DOD tenants
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/mscloudloginassistant/136)
> Updates for DOD and GCCH

- Modules/MSCloudLoginAssistant/ConnectionProfile.psm1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
- Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1
Fixed bug with connection to Graph for GCCH/DOD and added logic in SCC to support GCCH/DOD endpoints when connection is via SP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/143)
> Fixed Issue with SP Connection in GCCH/DOD

- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
- Fixes #141
- Fixes https://github.com/microsoft/Microsoft365DSC/issues/2915
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/142)
> Fixes for token refresh in MSGraph with AppSecret or Managed Identity

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
Updated SPO Admin URL retrieval
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/144)
> Updated SPO Admin URL retrieval

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This is a draft to improve the handling of changing authentication methods across all workloads. It will compare the Global values and the passed values. If there is a difference, it will reset the connection for the workload.
This change will fix the following issues:
- Fixes https://github.com/microsoft/Microsoft365DSC/issues/3067
- Fixes https://github.com/microsoft/Microsoft365DSC/issues/2964
@NikCharlebois and @ykuijs Could you perform some additional testing. I ran some tests but am not a 100% sure how this will impact overall performance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/148)
> Authentication Improvements - Improved handling of changes in authentication parameters

- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psd1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
Fixes an issue that breaks authentication
- Fixes https://github.com/microsoft/Microsoft365DSC/issues/3231
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/152)
> fixes https://github.com/microsoft/Microsoft365DSC/issues/3231

- Modules/MSCloudLoginAssistant/ConnectionProfile.psm1
- Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1
This PR will add additional refinements to the authentication process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/153)
> Additional refinements for authentication

- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
- Modules/MSCloudLoginAssistant/Workloads/PnP.psm1
Adding support to allow Azure Arc connected devices to use their System-Managed Identity to connect to the Graph API
Applies to:
- Microsoft Graph workload
- PnP workload
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/158)
> PR: Adding support for Azure Arc Connected Devices System Managed Identity 

- Modules/MSCloudLoginAssistant/Workloads/Tasks.psm1
Fixes #161
Added some handling to check if certificate was found in user store and if not alternate to machine store.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/162)
> [Workload Tasks] Certificates CurrentUser store

- Modules/MSCloudLoginAssistant/Workloads/MicrosoftGraph.psm1
This fixes issue #163.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/164)
> Fixed type conversion for MI login

- Modules/MSCloudLoginAssistant/Workloads/PnP.ps1
Adds the ability to specify a custom application id during e.g. export and also switches to using `-SPOManagementShell` to mitigate the missing PnP application in Entra. 
- Fixes #193
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/MSCloudLoginAssistant/194)
> Add possibility to use custom app registration
